---
name: release

on:
  workflow_dispatch:
    inputs:
      sha:
        description: The sha to associated with the release
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.set-up-go.outputs.go-version }}
      product-version: ${{ steps.set-product-version.outputs.product-version }}
      product-base-version: ${{ steps.set-product-version.outputs.base-product-version }}
      product-prerelease-version: ${{ steps.set-product-version.outputs.prerelease-product-version }}
      product-minor-version: ${{ steps.set-product-version.outputs.minor-product-version }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - id: set-up-go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
      - id: set-product-version
        uses: ./.github/actions/set-product-version
      - run: go mod download # so that the modules are cached

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        goos:
          - linux
          - darwin
        goarch:
          - amd64
          - arm64
    name: build ${{ matrix.goos }}/${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: hashicorp/actions-go-build@dd7ca5a30c402c933e1fe61e0ff7165e5c4ee9e4 # v1.1.2
        env:
          CGO_ENABLED: 0
          BASE_VERSION: ${{ needs.setup.outputs.product-base-version }}
          PRERELEASE_VERSION: ${{ needs.setup.outputs.product-prerelease-version}}
        with:
          bin_name: "terraform-provider-fyre_${{ needs.setup.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}"
          product_name: terraform-provider-fyre
          product_version: ${{ needs.setup.outputs.product-version }}
          go_version: ${{ needs.setup.outputs.go-version }}
          os: ${{ matrix.goos }}
          arch: ${{ matrix.goarch }}
          reproducible: report
          instructions: |
            go build \
              -o "$BIN_PATH" \
              -trimpath \
              -buildvcs=false
            cp LICENSE "$TARGET_DIR/LICENSE.txt"

  release:
    needs:
      - setup
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ inputs.sha }}   # checkout out our sha to get the version
      # Check out the enos-provider repository so we can use it's machinery
      # to publish the provider until it's available in the generic pipeline
      # tooling.
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: "hashicorp-forge/terraform-provider-enos"
          path: enos-provider
          token: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          pattern: terraform-provider-fyre_*
          merge-multiple: true
      - name: prepare dist
        run: |
          pushd dist
          ls -al
          unzip -o \*.zip
          rm -rf ./*.zip.json
          rm -rf ./*.zip
          rm LICENSE.txt
          chmod +x ./*
          ls -al
      - name: Import gpg key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create a Github release
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
        run: |
          gpg --list-signatures
          # actions/download-artifact doesn't preserve file permissions. Reset the exec bits.
          chmod 755 dist/*
          pushd enos-provider
          go run ./tools/publish/cmd github create \
            --provider-name fyre \
            --binary-name terraform-provider-fyre \
            --repo hashicorp-forge/terraform-provider-fyre \
            --dist ../dist \
            --gpg-key-id "${{ secrets.GPG_KEY_ID }}" \
            --commit "${{ inputs.sha }}" \
            --version "$(cat ../version/VERSION)" \
            --manifest-path ../terraform-registry-manifest.json
